#!/usr/bin/env bash

function require() {
	if ! dpkg -l "$1" | grep -q ^ii; then
		apt install "$@" -y
		. "$HOME/.bashrc"
	fi
}

trap 'echo "[$] $BASH_COMMAND"' DEBUG && set -e

apt update

# mbx
require git
if command -v "mbx-version" >/dev/null 2>&1; then
	mkdir -p /usr/local/mbx
	git clone --depth 1 https://github.com/martin-braun/mbx-toolbox.git /usr/local/mbx
	echo '' >> $HOME/.bashrc
	echo 'export PATH=$PATH:/usr/local/mbx/bin/deb:/usr/local/mbx/bin' >> $HOME/.bashrc
	echo "test -e /usr/local/mbx/lib/init.bash && . /usr/local/mbx/lib/init.bash" >> $HOME/.bashrc
	. "$HOME/.bashrc"
fi
. "$MBX_LIBPATH/_.bash"

# nvm / node
node_version=18
if ! test-command nvm; then
	require curl
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
	source $HOME/.bashrc
	nvm install $node_version
	nvm alias default $node_version
elif [ $(node -v | tr "." "\n" | head -1 2>&1) != "v$node_version"]; then
	nvm install $node_version
	nvm alias default $node_version
fi

# pm2
if ! test-command pm2; then
	npm i pm2 -g
fi

trap - DEBUG && echo "[o] Done!"

